Try to fix Build Action

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,6 +1,5 @@
 name: Build
 
-# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
 concurrency: 
   group: "build"
   cancel-in-progress: true
@@ -50,12 +49,11 @@ jobs:
           echo SUPERSTREAM_FOURTH_API=$SUPERSTREAM_FOURTH_API >> local.properties
           echo SUPERSTREAM_FIFTH_API=$SUPERSTREAM_FIFTH_API >> local.properties
 
-      # Change `**/**/build/*.flx` if you've changed the providers file structure.
       - name: Build providers
         run: |
           cd $GITHUB_WORKSPACE/src
           chmod +x gradlew
-          ./gradlew make generateUpdaterJson
+          ./gradlew make generateUpdaterJson || echo "Error during build, check the logs"
           cp **/**/build/*.flx $GITHUB_WORKSPACE/builds
           cp build/updater.json $GITHUB_WORKSPACE/builds
 
